import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>

          <div className="w-full min-h-screen flex flex-col items-center bg-sky-50/50">
            <header className="container flex flex-row bg-sky-300 py-6 px-8">
              <h1 className="grow text-gray-900 text-3xl">Webhooks</h1>
              <div className="">
                <SignedIn>
                  <UserButton afterSignOutUrl='/' />
                </SignedIn>
                <SignedOut>
                  <SignInButton />
                </SignedOut>
              </div>
            </header>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
